version: '3.5'
services:
  transmission:
    image: haugene/transmission-openvpn:latest
    container_name: transmission
    restart: always
    ports:
      - "9091:9091"
    environment:
      - PUID=1000
      - GUID=1000
      - OPENVPN_PROVIDER=PIA
      - OPENVPN_USERNAME=[REDACTED]
      - OPENVPN_PASSWORD=[REDACTED]
      - OPENVPN_CONFIG=[REDACTED]
      - CREATE_TUN_DEVICE=true
      - LOCAL_NETWORK=192.168.1.0/24, 172.10.30.0/24
      - WEBPROXY_ENABLED=false
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
      - TRANSMISSION_WEB_UI=transmission-web-control
      - TRANSMISSION_INCOMPLETE_DIR_ENABLED=false
      - TRANSMISSION_IDLE_SEEDING_LIMIT=100000
      - TRANSMISSION_IDLE_SEEDING_LIMIT_ENABLED=false
      - TRANSMISSION_PEER_LIMIT_GLOBAL=500
      - TRANSMISSION_DOWNLOAD_QUEUE_SIZE=100
      - TRANSMISSION_SEED_QUEUE_SIZE=800
      - TRANSMISSION_SEED_QUEUE_ENABLED=true
      - TRANSMISSION_RATIO_LIMIT_ENABLED=true
      - TRANSMISSION_RATIO_LIMIT=2
      - TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=true
      - TRANSMISSION_RPC_PASSWORD=[REDACTED]
      - TRANSMISSION_RPC_USERNAME=[REDACTED]
      - TRANSMISSION_DHT_ENABLED=false
      - TRANSMISSION_PEX_ENABLED=false
      - TRANSMISSION_PEER_PORT=51414
    cap_add:
      - NET_ADMIN
    volumes:
      - '/mnt/vmstorage/transmission:/data'
    networks:
      transmission-net: {}

networks:
  transmission-net:
    driver: bridge
    name: transmission-net
