version: '3.8'
services:

 homer:
  image: b4bz/homer:latest
  container_name: homer
  restart: unless-stopped
  environment:
  - UID=1000
  - GID=1000
  volumes:
  - '/data/homer/:/www/assets'
  labels:
  - "traefik.enable=true"
  - "traefik.http.routers.homer.rule=Host(`homer.apps.thedutchmc.nl`)"
  - "traefik.http.routers.homer.entrypoints=web"
  - "traefik.http.services.homer.loadbalancer.server.port=8080"
  - "traefik.docker.network=traefik-net"
  networks:
   traefik-net: {}

networks:
 traefik-net:
  external: true
