version: "3.8"
services:
 sonarr:
  image: linuxserver/sonarr
  container_name: sonarr
  devices:
  - /dev/fuse
  cap_add:
  - SYS_ADMIN
  environment:
  - PUID=1000
  - PGID=1000
  - TZ=Europe/Amsterdam
  volumes:
  - "/mnt/google_drive/tvshows:/tv"
#  - "/mnt/media/tvshows:/tv"
  - "/data/mediastack/sonarr:/config"
  - "/mnt/vmstorage/transmission/completed/supermicro1:/data/completed/supermicro1"
  restart: unless-stopped
  labels:
  - "traefik.enable=true"
  - "traefik.http.routers.sonarr.rule=Host(`sonarr.apps.thedutchmc.nl`)"
  - "traefik.http.routers.sonarr.entrypoints=web"
  - "traefik.http.services.sonarr.loadbalancer.server.port=8989"
  - "traefik.docker.network=traefik-net"
  networks:
    traefik-net: {}
    mediastack-net:
     ipv4_address: 172.10.20.2

 radarr:
  image: linuxserver/radarr
  container_name: radarr
  devices:
  - /dev/fuse
  cap_add:
  - SYS_ADMIN
  environment:
  - PUID=1000
  - PGID=1000
  - TZ=Europe/Amsterdam
  volumes:
  - "/mnt/google_drive/movies:/movies"
#  - "/mnt/media/movies:/movies"
  - "/data/mediastack/radarr:/config"
  - "/mnt/vmstorage/transmission/completed/supermicro1:/data/completed/supermicro1"
  restart: unless-stopped
  labels:
  - "traefik.enable=true"
  - "traefik.http.routers.radarr.rule=Host(`radarr.apps.thedutchmc.nl`)"
  - "traefik.http.routers.radarr.entrypoints=web"
  - "traefik.http.services.radarr.loadbalancer.server.port=7878"
  - "traefik.docker.network=traefik-net"
  networks:
    traefik-net: {}
    mediastack-net:
      ipv4_address: 172.10.20.3

 jackett:
  image: linuxserver/jackett
  container_name: jackett
  devices:
  - /dev/fuse
  cap_add:
  - SYS_ADMIN
  environment:
  - PUID=1000
  - GUID=1000
  - TZ=Europe/Amsterdam
  volumes:
  - "/data/mediastack/jackett:/config"
  - "/srv/torrent_downloads:/downloads"
  restart: unless-stopped
  labels:
  - "traefik.enable=true"
  - "traefik.http.routers.jackett.rule=Host(`jackett.apps.thedutchmc.nl`)"
  - "traefik.http.routers.jackett.entrypoints=web"
  - "traefik.http.services.jackett.loadbalancer.server.port=9117"
  - "traefik.docker.network=traefik-net"
  networks:
    traefik-net: {}
    mediastack-net:
      ipv4_address: 172.10.20.4

networks:
 traefik-net:
  external: true
 mediastack-net:
  driver: bridge
  enable_ipv6: false
  ipam:
   driver: default
   config:
   - subnet: "172.10.20.0/24"
 transmission-net:
   external:
     name: transmission-net
