---
title: "Dashboard"
subtitle: "Tobias de Bruijn"
logo: "custom/logo.png"
header: true
links: {}

#Optional theme customization
theme: default
colors:
  light:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#f5f5f5"
    card-background: "#ffffff"
    text: "#363636"
    text-header: "#ffffff"
    text-title: "#303030"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.1)
    link-hover: "#363636"
  dark:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#131313"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link-hover: "#ffdd57"

services:

  # Applications
  - name: "Applications"
    icon: "fas fa-cloud"
    items:
       - name: "Sonarr"
         logo: "assets/custom/sonarr.png"
         url: "https://sonarr.apps.thedutchmc.nl"
         target: "_blank"
       - name: "Radarr"
         logo: "assets/custom/radarr.png"
         url: "https://radarr.apps.thedutchmc.nl"
         target: "_blank"
       - name: "Bazarr"
         logo: "assets/custom/bazarr.png"
         url: "https://bazarr.apps.thedutchmc.nl"
         target: "_blank"
       - name: "Jackett"
         logo: "assets/custom/jackett.png"
         url: "https://jackett.apps.thedutchmc.nl"
         target: "_blank"
       - name: "Transmission"
         logo: "assets/custom/transmission.png"
         url: "https://transmission.apps.thedutchmc.nl"
         target: "_blank"
       - name: "Proxmox"
         logo: "assets/custom/proxmox.png"
         url: "https://proxmox.apps.thedutchmc.nl"
         target: "_blank"
       - name: "Traefik"
         logo: "assets/custom/traefik.png"
         url: "https://traefik.apps.thedutchmc.nl"
         target: "_blank"
       - name: "MariaDB"
         logo: "assets/custom/mariadb.png"
         url: "https://phpmyadmin.apps.thedutchmc.nl"
         target: "_blank"
       - name: "Gitea"
         logo: "assets/custom/gitea.png"
         url: "https://gitea.apps.thedutchmc.nl"
         target: "_blank"

  # Entertainment
  - name: "Entertainment"
    icon: "fas fa-cloud"
    items:
       - name: "Jellyfin"
         logo: "assets/custom/jellyfin.png"
         url: "https://media.thedutchmc.nl"
         target: "_blank"
       - name: "Netflix"
         logo: "assets/custom/netflix.png"
         url: "https://netflix.com"
         target: "_blank"
       - name: "YouTube"
         logo: "assets/custom/youtube.png"
         url: "https://youtube.com"
         target: "_blank"

  # Social media links
  - name: "Social Media"
    icon: "fas fa-cloud"
    items:
       - name: "Reddit"
         logo: "assets/custom/reddit.png"
         url: "https://reddit.com"
         target: "_blank"
       - name: "Twitter"
         logo: "assets/custom/twitter.png"
         url: "https://twitter.com"
         target: "_blank"
       - name: "Instagram"
         logo: "assets/custom/instagram.png"
         url: "https://instagram.com"
         target: "_blank"
       - name: "GitHub"
         logo: "assets/custom/github.png"
         url: "https://github.com"
         target: "_blank"
