---
title: "Dashboard"
subtitle: "Tobias de Bruijn"

logo: "/assets/custom/logo.png"

connectivityCheck: true

header: true
footer: ""
links: {}

#Optional theme customization
theme: default
colors:
  light:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#f5f5f5"
    card-background: "#ffffff"
    text: "#363636"
    text-header: "#ffffff"
    text-title: "#303030"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.1)
    link-hover: "#363636"
  dark:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#131313"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link-hover: "#ffdd57"

services:

  # Applications
  - name: "Applications"
    icon: "fas fa-server"
    items:
       - name: "Sonarr"
         subtitle: "Movies"
         logo: "assets/custom/sonarr.png"
         url: "https://sonarr.apps.thedutchmc.nl"
         target: "_top"

       - name: "Radarr"
         subtitle: "TV Shows"
         logo: "assets/custom/radarr.png"
         url: "https://radarr.apps.thedutchmc.nl"
         target: "_top"

       - name: "Lidarr"
         subtitle: "Music"
         logo: "assets/custom/lidarr.png"
         url: "https://lidarr.apps.thedutchmc.nl"
         target: "_top"

       - name: "Bazarr"
         subtitle: "Subtitles"
         logo: "assets/custom/bazarr.png"
         url: "https://bazarr.apps.thedutchmc.nl"
         target: "_top"

       - name: "Jackett"
         subtitle: "Torrent Indexer"
         logo: "assets/custom/jackett.png"
         url: "https://jackett.apps.thedutchmc.nl"
         target: "_top"

       - name: "Transmission"
         subtitle: "Torrent Download Client"
         logo: "assets/custom/transmission.png"
         url: "https://transmission.apps.thedutchmc.nl"
         target: "_top"

       - name: "Proxmox"
         logo: "assets/custom/proxmox.png"
         url: "https://proxmox.apps.thedutchmc.nl"
         target: "_top"

       - name: "Traefik"
         logo: "assets/custom/traefik.png"
         url: "https://traefik.apps.thedutchmc.nl"
         target: "_top"

       - name: "MariaDB"
         logo: "assets/custom/mariadb.png"
         url: "https://phpmyadmin.apps.thedutchmc.nl"
         target: "_top"

       - name: "Gitea"
         logo: "assets/custom/gitea.png"
         url: "https://gitea.apps.thedutchmc.nl"
         target: "_top"

       - name: "Portainer"
         logo: "assets/custom/portainer.png"
         url: "https://portainer.apps.thedutchmc.nl"
         target: "_top"

  # Entertainment
  - name: "Entertainment"
    icon: "fas fa-film"
    items:
       - name: "Jellyfin"
         logo: "assets/custom/jellyfin.png"
         url: "https://media.thedutchmc.nl"
         target: "_top"

       - name: "Netflix"
         logo: "assets/custom/netflix.png"
         url: "https://netflix.com"
         target: "_top"

       - name: "YouTube"
         logo: "assets/custom/youtube.png"
         url: "https://youtube.com"
         target: "_top"

  # Social media links
  - name: "Social Media"
    icon: "fas fa-hashtag"
    items:
       - name: "Reddit"
         logo: "assets/custom/reddit.png"
         url: "https://reddit.com"
         target: "_top"

       - name: "Twitter"
         logo: "assets/custom/twitter.png"
         url: "https://twitter.com"
         target: "_top"

       - name: "Instagram"
         logo: "assets/custom/instagram.png"
         url: "https://instagram.com"
         target: "_top"

       - name: "GitHub"
         logo: "assets/custom/github.png"
         url: "https://github.com"
         target: "_top"

  #Muce stuff
  - name: "Muce"
    icon: "fas fa-code"
    items:
       - name: "Muce Traefik"
         logo: "assets/custom/traefik.png"
         url: "http://192.168.1.201:8082/dashboard/#/"
         target: "_top"

       - name: "Muce Website"
         #logo: "assets/custom/reddit.png"
         url: "https://muce-code.github.io/muce"
         target: "_top"
