version: "3.3"
services:
  traefik:
    image: "traefik:v2.2"
    container_name: "traefik"
    restart: unless-stopped
    command:
      - "--log.level=INFO"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:8666"
      - "--accesslog=true"
      - "--accesslog.filepath=/srv/docker/traefik/access.log"
      - "--serverstransport.insecureskipverify=true"
      - "--entryPoints.ws.address=:9666"
    ports:
      - "8666:8666"
      - "8086:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./:/srv/docker/traefik"
    networks:
    - traefik-net

networks:
 traefik-net:
  external: true
