version: "3.3"
services:
  traefik:
    image: "traefik:v2.2"
    container_name: "traefik"
    restart: unless-stopped
    command:
      - "--log.level=INFO"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:8666"
      - "--accesslog=true"
      - "--accesslog.filepath=/srv/docker/traefik/access.log"
      - "--serverstransport.insecureskipverify=true"
    ports:
      - "8666:8666"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./:/srv/docker/traefik"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.apps.thedutchmc.nl`)"
      - "traefik.http.routers.traefik.entrypoints=web"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
      - "traefik.docker.network=traefik-net"
    networks:
      - traefik-net

networks:
  traefik-net:
    external: true
